name: C/C++ CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make
  upload-artifacts:
    - uses: actions/upload-artifact@v4
      with:
        name: bins
        path: bin/*